//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.PhoneServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneServiceReference.IPhoneService")]
    public interface IPhoneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/insertPhone", ReplyAction="http://tempuri.org/IPhoneService/insertPhoneResponse")]
        int insertPhone(int idPhone, int idBrand, string model, string os, string networkmode, string internalMemory, string externalMemory, int pixels, int flash, string resolution, int price, int quantity, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/insertPhone", ReplyAction="http://tempuri.org/IPhoneService/insertPhoneResponse")]
        System.Threading.Tasks.Task<int> insertPhoneAsync(int idPhone, int idBrand, string model, string os, string networkmode, string internalMemory, string externalMemory, int pixels, int flash, string resolution, int price, int quantity, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/getPhones", ReplyAction="http://tempuri.org/IPhoneService/getPhonesResponse")]
        Domain.Phone[] getPhones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/getPhones", ReplyAction="http://tempuri.org/IPhoneService/getPhonesResponse")]
        System.Threading.Tasks.Task<Domain.Phone[]> getPhonesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneServiceChannel : Test.PhoneServiceReference.IPhoneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneServiceClient : System.ServiceModel.ClientBase<Test.PhoneServiceReference.IPhoneService>, Test.PhoneServiceReference.IPhoneService {
        
        public PhoneServiceClient() {
        }
        
        public PhoneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertPhone(int idPhone, int idBrand, string model, string os, string networkmode, string internalMemory, string externalMemory, int pixels, int flash, string resolution, int price, int quantity, string image) {
            return base.Channel.insertPhone(idPhone, idBrand, model, os, networkmode, internalMemory, externalMemory, pixels, flash, resolution, price, quantity, image);
        }
        
        public System.Threading.Tasks.Task<int> insertPhoneAsync(int idPhone, int idBrand, string model, string os, string networkmode, string internalMemory, string externalMemory, int pixels, int flash, string resolution, int price, int quantity, string image) {
            return base.Channel.insertPhoneAsync(idPhone, idBrand, model, os, networkmode, internalMemory, externalMemory, pixels, flash, resolution, price, quantity, image);
        }
        
        public Domain.Phone[] getPhones() {
            return base.Channel.getPhones();
        }
        
        public System.Threading.Tasks.Task<Domain.Phone[]> getPhonesAsync() {
            return base.Channel.getPhonesAsync();
        }
    }
}
